---

- name: config env
  template: >
    src=config_{{ item[1] }}.ini.j2
    dest=/etc/php5/{{ item[0] }}/conf.d/70-config_{{ item[1] }}.ini
  notify:
    - php restart
  when: elao_env == item[1]
  with_nested:
    - [ 'cli', 'fpm' ]
    - [ 'dev', 'prod' ]
  sudo: yes

- name: config env not
  file: >
    path=/etc/php5/{{ item[0] }}/conf.d/70-config_{{ item[1] }}.ini
    state=absent
  notify:
    - php restart
  when: not elao_env == item[1]
  with_nested:
    - [ 'cli', 'fpm' ]
    - [ 'dev', 'prod' ]
  sudo: yes

# Todo : Find a way to merge cli/fpm config with a default one

# Todo : Remove config files (global & specific) when config dicts are empty
# ! careful to php 5.4 where conf.d is a symbolic link to ../conf.d

- name: config global cli
  ini_file: >
    dest=/etc/php5/cli/conf.d/80-config.ini
    section=PHP
    option={{ item.key }}
    value={{ item.value }}
  when: elao_php_config|length > 0
  with_dict: elao_php_config
  sudo: yes

- name: config global fpm
  ini_file: >
    dest=/etc/php5/fpm/conf.d/80-config.ini
    section=PHP
    option={{ item.key }}
    value={{ item.value }}
  when: elao_php_config|length > 0
  with_dict: elao_php_config
  sudo: yes

# Todo : specific configs should be ignored in case
# /etc/php5/[env]/conf.d is a symbolic link to ../conf.d

- name: config specific cli
  ini_file: >
    dest=/etc/php5/cli/conf.d/90-config_cli.ini
    section=PHP
    option={{ item.key }}
    value={{ item.value }}
  when: elao_php_config_cli|length > 0
  with_dict: elao_php_config_cli
  sudo: yes

- name: config specific fpm
  ini_file: >
    dest=/etc/php5/fpm/conf.d/90-config_fpm.ini
    section=PHP
    option={{ item.key }}
    value={{ item.value }}
  when: elao_php_config_fpm|length > 0
  with_dict: elao_php_config_fpm
  sudo: yes

# Configuring FPM Pools
- name: config fpm pools
  template: >
    src=pool.conf.j2
    dest={{ elao_php_fpm_pools_path }}/{{ item.key }}.conf
  notify:
    - php restart
  with_dict: elao_php_fpm_pools
  sudo: yes

# Todo : Clean old pools
