---

- name: packages pinning
  template: >
    src=pinning.j2
    dest=/etc/apt/preferences.d/php
  sudo: yes

- name: repositories key
  apt_key: >
    url=http://www.dotdeb.org/dotdeb.gpg
    state=present
  sudo: yes

- name: repositories
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org {{ ansible_distribution_release }} all
  sudo: yes

- name: repositories 5.5
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org {{ ansible_distribution_release }}-php55 all
  when: elao_php_version == 5.5
  sudo: yes

- name: repositories not 5.5
  apt_repository: >
    repo="{{ item }}"
    state=absent
    update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org {{ ansible_distribution_release }}-php55 all
  when: not elao_php_version == 5.5
  sudo: yes

# Todo : Suffix package names by "={{ elao_php_version }}.*" when bug fixed
# See : https://github.com/ansible/ansible/issues/6885

- name: packages
  apt: >
    name={{ item }}
    state=latest
    force=yes
  with_items:
    - php5-cli
    - php5-fpm
  sudo: yes
